// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace WebApplication1.Models
{
    public partial class Product
    {
        [Required(ErrorMessage = "Id không được để trống")]
        public string Id { get; set; }
        [Required(ErrorMessage = "Sản phẩm không được để trống")]
        public string ProductName { get; set; }
        [Required(ErrorMessage = "Giá không được để trống")]
        public string Price { get; set; }
        [Required(ErrorMessage = "Mô tả không được để trống")]
        public string Description { get; set; }
        public byte[] CreatedBy { get; set; }
        public DateTime? UpdatedBy { get; set; }
    }

}